### ISSUE TITLE
dosnt work for me im using minehut

### ISSUE THREAD

**Issue by sqnas1** [mehboss/CustomRecipes#23]
### What happened?

it dosnt work and i think its bc im using minehut?

### What was supposed to happen?

?

### How do I reproduce this issue?

```bash
1.
2.
3.
...
```

### Relevant log output

```shell
e
```

### Relevant file configuration

```shell
e
```

### Server Version

1.20.1

### Plugin Version

paper

### Server Mode

Online Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of custom recipes and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by Valorless** [comment]
I'm sorry but I don't quite understand what you mean.
What is the issue you're having?
Is anything shown, such as is the console?

**Comment by mehboss** [comment]
As said by Valorless, more information is needed in order to proceed with the resolution. I am unable to replicate this issue and do not use Minehut.

- Can you provide us with a pastebin link of the console log upon starting up the server and loading all active plugins?
- Is the plugin enabled? Can you see it when you do /pl?

Have you tried:

- Shutting the server completely down
- Importing CustomRecipes.jar into the plugins folder
- Starting up the server again.

Once this information is provided, we can then try to troubleshoot and suggest ways to fix this issue.

Thank you

**Comment by mehboss** [comment]
Hello,

I am closing this ticket as I can not replicate it and do not have the information needed to proceed with resolution. If this problem still persists, please open another ticket with the requested info above this post.

Thank you.
